name: CommentWorkflow
on:
  issue_comment:
    types: [created]
jobs:
  wait_for_resource:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/re-build')
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge emoji
        uses: actions-cool/emoji-helper@v1.0.0
        with:
          type: 'comment'
          emoji: '+1'
          token: ${{secrets.GH_TOKEN}}
          comment-id: ${{github.event.comment.id}}
      - uses: actions/checkout@v2
      - run: ls
      - uses: actions/github-script@v6
        id: script
        with:
          script: |
            const script = require('./script.js')
            const userId = await script(context)
            return userId
          result-encoding: string
      - name: Get userId
        run: echo "${{steps.script.outputs.result}}"
      - name: Tag User
        uses: actions-cool/issues-helper@v2
        with:
          actions: 'create-comment'
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: |
            @${{steps.script.outputs.result}} 
